fix(translate-json-object): make valid audit report
KhaledMohamedP/translate-json-object pull request #16
Opened 2019-03-12 12:44 UTC by sp90

Fixes #10

2019-03-13 04:21 UTC, KhaledMohamedP commented
Can you please resolve the travis-ci build issue, so I can merge this PR. Let me know if any action is required from my end. Thank you!

2019-03-13 14:20 UTC, sp90 commented
It can't be done some of the dev dependancies require higher than node 4.x - so it's time to leave this legacy version behind and focusing on newer versions

2019-03-14 03:09 UTC, KhaledMohamedP requested changes
Can you please address the comments below before I can merge this PR!

2019-03-14 03:09 UTC, KhaledMohamedP commented on package.json
> +    "semantic-release": "^15.13.4",
Can you please remove `^` from the dependencies versions

2019-03-14 03:09 UTC, KhaledMohamedP commented on .travis.yml
> -  - '4'
Since this is breaking change, we should indicate this in the commit message

2019-03-14 03:18 UTC, KhaledMohamedP commented
Since we are supporting newer version of `npm`, we need to commit the generated `package-lock.json` file too. 

I really appreciate your help here 😄

2019-03-14 13:45 UTC, sp90 commented
@KhaledMohamedP Added in the latest commit

2019-03-14 15:45 UTC, KhaledMohamedP commented
@sp90 can you address the following comments

- https://github.com/KhaledMohamedP/translate-json-object/pull/16#discussion_r265406071
- https://github.com/KhaledMohamedP/translate-json-object/pull/16#discussion_r265405504

 also please fix Travis-CI, so I can merge in the code

2019-03-15 11:07 UTC, sp90 commented
@KhaledMohamedP Can't fix it for you because its the travis cache that dosn't match the package versions so you need to clear the travis caches or give me access

2019-03-15 15:20 UTC, KhaledMohamedP commented
@sp90 I cleared the cache and re-build this PR and it worked. 

However `semantic-release` changed their API!

 I tested this command for publishing the package and it doesn't seems to work  anymore 

`"semantic-release": "semantic-release pre && npm publish && semantic-release post",`

We will need to accommodate for the new api changes if we want to update the `semantic-release` package 😞 

https://semantic-release.gitbook.io/semantic-release/usage/configuration

2019-03-19 08:34 UTC, sp90 commented
Please check the updates

2019-03-19 18:02 UTC, KhaledMohamedP commented
Since the build is failing, I went ahead and created a PR that upgrades Node.js and some other core dependencies!

Thank you for addressing this issue 🙏

2019-03-19 18:02 UTC, closed without merging

2019-03-22 08:22 UTC, sp90 commented
Thanks for taking away my contribution 👍 i just love to give away my time without getting credit

/Cheers